# ç½‘ç«™åŸºæœ¬ä¿¡æ¯
title: "my secret recipes ğŸ³"
description: "yummy yummy"
baseurl: "/The-Secret-Ingredient"
# url: "https://ä½ çš„ç”¨æˆ·å.github.io" # æ›¿æ¢ä¸ºä½ çš„GitHubç”¨æˆ·å

# ä½œè€…ä¿¡æ¯
author:
  name: "Madeline_"
  email: "zMx202305@gmail.com"

# ä¸»é¢˜å’Œå¤–è§‚
theme: minima
minima:
  skin: auto # æ”¯æŒæ·±è‰²æ¨¡å¼
  social_links:
    github: MuxuZhao

# æ’ä»¶
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# èœè°±åˆ†ç±»
collections:
  recipes:
    output: true
    permalink: /recipes/:name/

# é»˜è®¤è®¾ç½®
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Madeline's grandmother"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"

# ç½‘ç«™è®¾ç½®
show_excerpts: true
paginate: 5
