# ç½‘ç«™åŸºæœ¬ä¿¡æ¯
title: "my secret recipes ğŸ³"
description: "yummy yummy yummy yummy yummy"
baseurl: "/The-Secret-Ingredient"
url: "https://MuxuZhao.github.io"

# ä½œè€…ä¿¡æ¯
author: "Madeline_"
email: "zMx202305@gmail.com"

# ä¸»é¢˜å’Œå¤–è§‚
theme: minima
minima:
  skin: auto 
  social_links:
    github: MuxuZhao

# æ’ä»¶
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# ç½‘ç«™è®¾ç½®
show_excerpts: true
paginate: 5
